# Author: Salo Shp <saloshp@gmail.com>
#
#    This file is part of Munio. <https://github.com/salosh/munio.git>
#
#    Munio is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Munio is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Munio.  If not, see <http://www.gnu.org/licenses/>.
#

---
pacman:
  packages:
  - bind
  - bind-tools
  services:
  - named

apt:
  packages:
  - bind9
  - bind9utils
  services:
  - bind9

yum:
  packages:
  - bind
  - bind-utils
  services:
  - named

conf: "{{ vars[ansible_pkg_mgr] | default({}) }}"
bind_host: "{{ ips[cnc_net][inventory_hostname].ip }}"
#bind_port: "12345"

service_final:
  state: "restarted"
  enabled: "yes"

