# Author: Salo Shp <saloshp@gmail.com>
#
#    This file is part of Munio. <https://github.com/salosh/munio.git>
#
#    Munio is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Munio is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Munio.  If not, see <http://www.gnu.org/licenses/>.
#

---
- name: "Configure proxy"
  import_tasks: "./proxy.yml"

- name: "Configure grub"
  import_tasks: "./grub.yml"

- name: "Configure networking"
  import_tasks: "./network.yml"

- name: "Configure DNS settings"
  import_tasks: "./dns.yml"

- name: "Configure operating-system settings"
  import_tasks: "./os.yml"

- name: "Install packages"
  import_tasks: "./bin.yml"

- name: "Run final action '{{ sysconf_final_op }}'"
  shell: |
      {% set cmd = [] %}
      {% set tmp = cmd.append('sleep 2') %}
      {% set tmp = cmd.append('&&') %}
      {% if sysconf_final_op in ['reboot', 'restart'] %}
      {%   set tmp = cmd.append('shutdown -r now') %}
      {% elif sysconf_final_op in ['shutdown', 'stop', 'destroy'] %}
      {%   set tmp = cmd.append('shutdown -h now') %}
      {% endif %}
      {% set tmp = cmd.append('"Ansible triggered restart"') %}
      {{ (cmd | join(' ') ) }}
  async: 1
  poll: 0
  become: yes
  ignore_errors: true
  when:
  - "sysconf_final_op is defined"
  - "sysconf_final_op != 'NOP'"
  tags:
  - conf

#    host={{ ips[cnc_net][inventory_hostname].ip }}
- name: "Wait for nodes to complete reboot"
  local_action:
    wait_for
    host={{ hostvars[inventory_hostname].ansible_host }}
    port={{ hostvars[inventory_hostname].ansible_port }}
    search_regex="OpenSSH"
    delay=30
    timeout=541
  failed_when: false
  when:
  - "sysconf_final_op is defined"
  - "sysconf_final_op == 'reboot'"
  tags:
  - conf
