# Author: Salo Shp <saloshp@gmail.com>
#
#    This file is part of Munio. <https://github.com/salosh/munio.git>
#
#    Munio is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Munio is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Munio.  If not, see <http://www.gnu.org/licenses/>.
#

---
- name: "Deploy proxy configuration"
  copy:
    content: "{{ item.content }}"
    dest:    "/etc/apt/apt.conf.d/{{ item.name }}"
  loop:
  - name:    "05-http-proxy"
    content: "Acquire::http::Proxy \"{{ proxy.protocol }}://{{ proxy.host }}:{{ proxy.port }}\";"
  - name:    "05-https-proxy"
    content: "Acquire::https::Proxy \"{{ proxy.protocol }}://{{ proxy.host }}:{{ proxy.port }}\";"
  when:
  - proxy is defined
  - proxy.enabled | bool
  tags:
  - conf

# TODO Ansible key
#apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367
#wget -O - "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x93C4A3FD7BB9C367" | apt-key add -
# only store keys
