# Author: Salo Shp <saloshp@gmail.com>
#
#    This file is part of Munio. <https://github.com/salosh/munio.git>
#
#    Munio is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Munio is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Munio.  If not, see <http://www.gnu.org/licenses/>.
#

---
- name: "common :: Force update packages packages using '{{ ansible_pkg_mgr }}'"
  environment:
    http_proxy:  "{{ proxy.protocol }}://{{ proxy.host }}:{{ proxy.port }}"
    https_proxy: "{{ proxy.protocol }}://{{ proxy.host }}:{{ proxy.port }}"
  shell:
    "{{ shell_cmd }}"
  with_items:
  - "dpkg --configure -a || /bin/true"
  - "apt-get -f install"
  - "apt -o Debug::Acquire::http::Proxy=${http_proxy} -o Debug::Acquire::https::Proxy=${https_proxy} update -y"
  when:
  - apt_hotfix is defined
  - apt_hotfix | bool
  loop_control:
    loop_var: "shell_cmd"
  tags:
  - bin

- name: "common :: Install required packages using '{{ ansible_pkg_mgr }}'"
  environment:
    http_proxy:  "{{ proxy.protocol }}://{{ proxy.host }}:{{ proxy.port }}"
    https_proxy: "{{ proxy.protocol }}://{{ proxy.host }}:{{ proxy.port }}"
  apt:
    name: "{{ pkg_name }}"
    state: present
  with_items:
  - "{{ packages }}"
  loop_control:
    loop_var: "pkg_name"
  tags:
  - bin

