# Author: Salo Shp <saloshp@gmail.com>
#
#    This file is part of Munio. <https://github.com/salosh/munio.git>
#
#    Munio is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Munio is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Munio.  If not, see <http://www.gnu.org/licenses/>.
#

---
- name: "common :: Full system upgrade using '{{ ansible_pkg_mgr }}'"
  environment:
    UCF_FORCE_CONFFNEW: YES
    DEBIAN_FRONTEND: noninteractive
    http_proxy:  "{{ proxy.protocol }}://{{ proxy.host }}:{{ proxy.port }}"
    HTTP_PROXY:  "{{ proxy.protocol }}://{{ proxy.host }}:{{ proxy.port }}"
    https_proxy: "{{ proxy.protocol }}://{{ proxy.host }}:{{ proxy.port }}"
    HTTPS_PROXY: "{{ proxy.protocol }}://{{ proxy.host }}:{{ proxy.port }}"
  shell:
    "{{ item }}"
  with_items:
  - "dpkg --configure -a || /bin/true"
  - "apt-get -f install"
  - "ucf --purge /boot/grub/menu.lst"
  - "apt-get update -y --force-yes || apt-get -o Acquire::CompressionTypes::Order::=gz update -y --force-yes"
  - "apt-get -o Dpkg::Options::=\"--force-confnew\" --force-yes -fuy upgrade"
  tags:
  - bin

# TODO FIXME /bin/true
