# Author: Salo Shp <saloshp@gmail.com>
#
#    This file is part of Munio. <https://github.com/salosh/munio.git>
#
#    Munio is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Munio is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Munio.  If not, see <http://www.gnu.org/licenses/>.
#

---
- name: "Install packages"
  vars:
    packages: "{{ conf.packages }}"
  include_tasks: "{{ role_path }}/../common/tasks/{{ ansible_pkg_mgr }}/package.yml"
  tags:
  - bin

- name: "Stop service"
  service:
    name:    "{{ item }}"
    state:   stopped
    enabled: no
  with_items:
  - "{{ conf.services }}"
  tags:
  - service

- name: "Deploy '{{ ansible_pkg_mgr }}' based configuration"
  include_tasks: "./conf_{{ ansible_pkg_mgr }}.yml"

- name: "Final state for service - {{ service_final.state }}"
  service:
    name:    "{{ item }}"
    state:   "{{ service_final.state }}"
    enabled: "{{ service_final.enabled }}"
  with_items:
  - "{{ conf.services }}"
  tags:
  - service

# TODO XXX remove this ugliness
# Doesnt actually verify binding to the right host, 0.0.0.0 parsed as *
# Ansible wait_for doesn't support UDP
- name: "Wait for ports"
  shell:
    "lsof -nP -i :{{ item.port }} || sleep 5 && lsof -nP -i :{{ item.port }}"
  with_items:
  - host: "{{ bind_host | d('127.0.0.1') }}"
    port: "{{ bind_port | d('53') }}"
  loop_control:
    label: "UDP {{ item.host }}:{{ item.port }}"
  when:
  - "service_final.state != 'stopped'"
  tags:
  - service
  - verify

- name: "Verify DNS functionality - internal"
  shell: |
      {% set cmd = 'nslookup -debug ' ~ item ~ '.' ~ fqdn ~ ' ' ~  bind_host %}
      {{ (cmd) }}
  with_items:
  - "{{ groups['dns-nodes'] }}"
  loop_control:
    label: "'{{ inventory_hostname }}' verifies internal DNS resolving to '{{ item }}'"
  tags:
  - service
  - verify

- name: "Verify DNS functionality - external DNS servers"
  shell: |
      {% set cmd = 'nslookup -debug ' ~ item ~ ' ' ~  bind_host %}
      {{ (cmd) }}
  with_items:
  - "{{ external_dns }}"
  when:
  - "external_dns | length > 0"
  loop_control:
    label: "'{{ inventory_hostname }}' verifies internal DNS resolving to '{{ item }}'"
  tags:
  - service
  - verify

- name: "Verify DNS functionality - external"
  shell: |
      {% set cmd = 'nslookup -debug ' ~ item ~ ' ' ~ bind_host %}
      {{ (cmd) }}
  with_items:
  - munio.io
  loop_control:
    label: "'{{ inventory_hostname }}' verifies external DNS resolving to '{{ item }}'"
  when:
  - "connectivity_mode == 'online'"
  tags:
  - service
  - verify
