# Author: Salo Shp <saloshp@gmail.com>
#
#    This file is part of Munio. <https://github.com/salosh/munio.git>
#
#    Munio is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Munio is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Munio.  If not, see <http://www.gnu.org/licenses/>.
#

---
pacman:
  pre_packages: []
  packages:
  - rpcbind
  - glusterfs
  services:
  - rpcbind
  - glusterd
  username:  "root"
  groupname: "root"
  files:
  - name: "default.yml"
    path: "/tmp"
  root_dir:  "/srv/gfs"

apt:
  pre_packages: []
  packages:
  - "glusterfs-server"
  services: []
  username:  "default"
  groupname: "default"
  files:
  - name: "default.yml"
    path: "/tmp"
  root_dir:  "/srv/gfs"

yum:
  pre_packages:
  - "centos-release-gluster37"
  packages:
  - "glusterfs"
  - "glusterfs-cli"
  - "glusterfs-libs"
  - "glusterfs-server"
  services:
  - "glusterd"
  username:  "root"
  groupname: "root"
  files:
  - name: "default.yml"
    path: "/tmp"
  root_dir:  "/srv/gfs"

bricks:
  - name:     "brick1"
    dev_name: "/dev/sdb"
    vg_name:  gfs
    size:     "50%FREE"
  - name:     "brick2"
    dev_name: "/dev/sdb"
    vg_name:  gfs
    size:     "100%FREE"

conf: "{{ vars[ansible_pkg_mgr] | default({}) }}"

shared_volume:
  name: "gv1"
  path: "{{ conf.root_dir }}/shared"

bind_host: "{{ ips[cnc_net][inventory_hostname].ip }}"
bind_port: "24007"

service_final:
  state:   "restarted"
  enabled: "yes"

