# Author: Salo Shp <saloshp@gmail.com>
#
#    This file is part of Nylox. <https://github.com/nylox/nylox.git>
#
#    Nylox is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Nylox is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Nylox.  If not, see <http://www.gnu.org/licenses/>.
#

---
- name: "Download requirements"
  include_tasks: "{{ role_path }}/../common/tasks/requirements.yml"
  when:
  - "connectivity_mode == 'online'"
  tags:
  - reqs

- name: "Create OS groups"
  group:
    name:   "{{ conf.groupname }}"
    system: "yes"
    state:  "present"
  tags:
  - init

- name: "Create OS users"
  user:
    name:      "{{ conf.username }}"
    group:     "{{ conf.groupname }}"
    append:    "yes"
    shell:     "/bin/false"
    home:      "/var/lib/{{ conf.username }}"
    move_home: "yes"
    system:    "yes"
    state:     "present"
  tags:
  - init

- name: "Extract binary '{{ requirements.binary.name }}'"
  unarchive:
    src:  "{{ requirements.binary.local_path }}"
    dest: "/usr/share"
    owner: "{{ conf.username }}"
    group: "{{ conf.username }}"
    mode: "u=rwx,g=rx,o=rx"
  tags:
  - bin

- name: "Create working directory link"
  file:
    src: "{{ conf.work_dir }}-{{ elasticsearch_version }}"
    dest: "{{ conf.work_dir }}"
    state: link
    owner: "{{ conf.username }}"
    group: "{{ conf.username }}"
    mode:  "u=rwx,g=rx,o=rx"
    force: yes

- name: "Create binary links"
  file:
    src: "../share/elasticsearch-{{ elasticsearch_version }}/bin/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    state: link
    owner: "{{ conf.username }}"
    group: "{{ conf.username }}"
    mode:  "u=rwx,g=rx,o=rx"
    force: yes
  with_items:
  - "elasticsearch-env"
  - "elasticsearch"

- name: "Deploy service file"
  template:
    src:   elasticsearch_systemd.j2
    dest:  /etc/systemd/system/elasticsearch.service
    owner: root
    group: root
    mode:  "u=rw,g=r,o=r"
  tags:
  - service

- name: "Stop service"
  service:
    name:    "{{ item }}"
    state:   stopped
    enabled: no
  with_items:
  - "{{ conf.services }}"
  tags:
  - service

- name: "Deploy '{{ ansible_pkg_mgr }}' based configuration"
  include_tasks: "./conf_{{ ansible_pkg_mgr }}.yml"

- name: "Create required directories"
  file:
    path:  "{{ item }}"
    state: "directory"
    owner: "{{ conf.username }}"
    group: "{{ conf.groupname }}"
    mode: "u=rwx,g=rwx,o=rx"
  with_items:
  - "{{ conf.conf_dir }}"
  - "{{ conf.root_dir }}"
  - "{{ conf.log_dir }}"
  tags:
  - conf

- name: "Create directory links"
  file:
    src: "{{ conf.log_dir }}"
    dest: "{{ conf.work_dir }}-{{ elasticsearch_version }}/logs"
    state: link
    owner: "{{ conf.username }}"
    group: "{{ conf.username }}"
    mode:  "u=rwx,g=rx,o=rx"
    force: yes

- name: "Deploy configuration"
  template:
    src:   "{{ item }}.j2"
    dest:  "{{ conf.conf_dir }}/{{ item }}"
    owner: "{{ conf.username }}"
    group: "{{ conf.groupname }}"
    mode: "u=rwx,g=rwx,o=rx"
    force: yes
  with_items:
  - "elasticsearch.yml"
  - "log4j2.properties"
  - "jvm.options"
  tags:
  - conf

- name: "Deploy advanced memory settings"
  sysctl: name={{ item.key }} value={{ item.value }}
  with_items:
  - { key: "vm.max_map_count", value: 262144 }
  tags:
  - conf

- name: "Final state for service - {{ service_final.state }}"
  service:
    name:    "{{ item }}"
    state:   "{{ service_final.state }}"
    enabled: "{{ service_final.enabled }}"
  with_items:
  - "{{ conf.services }}"
  tags:
  - service

- name: "Wait for ports"
  wait_for:
    host:    "{{ item.host }}"
    port:    "{{ item.port }}"
    state:   started
    timeout: 30
  with_items:
  - host: "{{ bind_host | d('127.0.0.1') }}"
    port: "{{ bind_port | d('9200') }}"
  loop_control:
    label: "{{ item.host }}:{{ item.port }}"
  when:
  - "service_final.state != 'stopped'"
  tags:
  - service
  - verify


# Debug total number of items
# curl -XGET 'http://elasticsearch.service.lb:9200/telegraf-*/metrics/_search?size=0' -H "Content-Type: application/json" | python -m json.tool
# curl -XDELETE 'http://elasticsearch.service.lb:9200/telegraf-*'
