# Author: Salo Shp <saloshp@gmail.com>
#
#    This file is part of Munio. <https://github.com/salosh/munio.git>
#
#    Munio is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Munio is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Munio.  If not, see <http://www.gnu.org/licenses/>.
#

---
conf:
  services:
  - etcd
  username: "etcd"
  groupname: "etcd"
  root_dir: /var/lib/etcd
  conf_file: conf.yml
  conf_dir: /etc/etcd
  work_dir: /usr/share/etcd

etcd_version: "3.3.9"
etcd_download_uri: "https://github.com/coreos/etcd/releases/download/v{{ etcd_version }}"

requirements:
  binary:
    type:        "uri"
    name:        "etcd-v{{ etcd_version }}-linux-amd64.tar.gz"
    remote_path: "{{ etcd_download_uri }}/etcd-v{{ etcd_version }}-linux-amd64.tar.gz"
    local_path:  "{{ dir_reqs }}/etcd-v{{ etcd_version }}-linux-amd64.tar.gz"
    sha256:      "7b95bdc6dfd1d805f650ea8f886fdae6e7322f886a8e9d1b0d14603767d053b1"


bind_host: "{{ ips[cnc_net][inventory_hostname].ip }}"
#bind_port: "2379,2380"

service_final:
  state:   "restarted"
  enabled: "yes"

