# Author: Salo Shp <saloshp@gmail.com>
#
#    This file is part of Munio. <https://github.com/salosh/munio.git>
#
#    Munio is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Munio is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Munio.  If not, see <http://www.gnu.org/licenses/>.
#

---
- hosts: ha-nodes
##  strategy: free
#  gather_facts: no
#  no_log: True
  roles:
  - { role: sysconf, sysconf_final_op: "reboot" }

- import_playbook: "./dns.yml"
- import_playbook: "./rootca.yml"
#- import_playbook: "./consul.yml"
- import_playbook: "./etcd.yml"
- import_playbook: "./coredns.yml"
- import_playbook: "./todero.yml"
- import_playbook: "./ldap.yml"
- import_playbook: "./kerberos.yml"
- import_playbook: "./vault.yml"


#- import_playbook: "./kubernetes.yml"
#- import_playbook: "./mariadb.yml"
#- import_playbook: "./rabbitmq.yml"
#- import_playbook: "./glusterfs.yml"
#- import_playbook: "./elasticsearch.yml"
#- import_playbook: "./telegraf.yml"

- hosts: ha-nodes
##  strategy: free
#  gather_facts: no
#  no_log: True
  roles:
  - { role: http, bind_port: 8080 }
  - { role: nginx, bind_port: 80, vault_host: "ha01", vault_port: 8200, ssl_path_cert: "/etc/nginx/nginx.crt", ssl_path_key: "/etc/nginx/nginx.key"}

